function byId(id){return document.getElementById(id)}
function val(id){const v=parseFloat(byId(id)?.value);return isNaN(v)?0:v}
function fmt(n,d=6){if(!isFinite(n))return"Invalid";return Number(n.toFixed(d)).toLocaleString("en-IN")}
function filterCards(){const q=byId("siteSearch")?.value.toLowerCase().trim()||"";document.querySelectorAll("[data-search]").forEach(c=>{c.style.display=c.dataset.search.toLowerCase().includes(q)?"":"none"})}
function calcKgMt(){let a=val("kgmt_amount"),f=byId("kgmt_from").value;let kg=f==="kg"?a:f==="g"?a/1000:a*1000;let mt=kg/1000;byId("kgmt_result").innerHTML=`<strong>${fmt(kg,3)} KG</strong><br><strong>${fmt(mt,6)} MT</strong><br><span class="small">${fmt(kg*1000,3)} Gram</span>`}
function calcLiterMt(){let a=val("liter_amount"),f=byId("liter_from").value,d=val("density");let liter=f==="liter"?a:f==="kl"?a*1000:f==="ml"?a/1000:a*1000;let kg=liter*d,mt=kg/1000;byId("liter_result").innerHTML=`<strong>${fmt(liter,3)} Liter</strong><br><strong>${fmt(kg,3)} KG</strong><br><strong>${fmt(mt,6)} MT</strong>`}
function calcSm3Mt(){let a=val("sm3_amount"),f=byId("sm3_from").value,d=val("gas_density");let kg=f==="sm3"?a*d:f==="kg"?a:a*1000;let sm3=d?kg/d:0,mt=kg/1000;byId("sm3_result").innerHTML=`<strong>${fmt(sm3,3)} Sm³</strong><br><strong>${fmt(kg,3)} KG</strong><br><strong>${fmt(mt,6)} MT</strong>`}
function calcGST(){let a=val("gst_amount"),r=val("gst_rate"),m=byId("gst_mode").value;let taxable,gst,total;if(m==="exclusive"){taxable=a;gst=a*r/100;total=taxable+gst}else{total=a;taxable=a/(1+r/100);gst=total-taxable}byId("gst_result").innerHTML=`<strong>Taxable: ₹${fmt(taxable,2)}</strong><br><strong>GST: ₹${fmt(gst,2)}</strong><br><strong>Total: ₹${fmt(total,2)}</strong>`}
function calcPercentAmount(inputId,percentId,resultId,label){let b=val(inputId),p=val(percentId),v=b*p/100;byId(resultId).innerHTML=`<strong>${label}: ₹${fmt(v,2)}</strong><br><span class="small">${p}% of ₹${fmt(b,2)}</span>`}
function calcPercentage(){let a=val("percent_part"),b=val("percent_total");byId("percentage_result").innerHTML=`<strong>${fmt((a/b)*100,2)}%</strong><br><span class="small">${fmt(a,2)} is this percent of ${fmt(b,2)}</span>`}
function calcDiscount(){let p=val("discount_price"),d=val("discount_rate");let save=p*d/100,final=p-save;byId("discount_result").innerHTML=`<strong>Final Price: ₹${fmt(final,2)}</strong><br><strong>You Save: ₹${fmt(save,2)}</strong>`}
function calcProfitLoss(){let cost=val("cost_price"),sell=val("sell_price");let diff=sell-cost,per=cost?diff/cost*100:0;let label=diff>=0?"Profit":"Loss";byId("profit_result").innerHTML=`<strong>${label}: ₹${fmt(Math.abs(diff),2)}</strong><br><strong>${label} %: ${fmt(Math.abs(per),2)}%</strong>`}
function calcEMI(){let p=val("loan_amount"),annual=val("loan_rate"),months=val("loan_months"),r=annual/12/100;let emi=r?p*r*Math.pow(1+r,months)/(Math.pow(1+r,months)-1):p/months;let total=emi*months;byId("emi_result").innerHTML=`<strong>EMI: ₹${fmt(emi,2)}</strong><br><strong>Total Payment: ₹${fmt(total,2)}</strong><br><span class="small">Interest: ₹${fmt(total-p,2)}</span>`}
function calcSIP(){let m=val("sip_amount"),annual=val("sip_rate"),months=val("sip_months"),r=annual/12/100;let fv=r?m*(Math.pow(1+r,months)-1)*(1+r)/r:m*months;let invest=m*months;byId("sip_result").innerHTML=`<strong>Future Value: ₹${fmt(fv,2)}</strong><br><strong>Invested: ₹${fmt(invest,2)}</strong><br><span class="small">Gain: ₹${fmt(fv-invest,2)}</span>`}
function calcFD(){let p=val("fd_amount"),annual=val("fd_rate"),years=val("fd_years"),n=val("fd_compound");let maturity=p*Math.pow(1+annual/(100*n),n*years);byId("fd_result").innerHTML=`<strong>Maturity: ₹${fmt(maturity,2)}</strong><br><span class="small">Interest: ₹${fmt(maturity-p,2)}</span>`}
function calcAge(){let dob=byId("dob").value;if(!dob){byId("age_result").innerHTML="Select date of birth.";return}let birth=new Date(dob),today=new Date();let y=today.getFullYear()-birth.getFullYear(),m=today.getMonth()-birth.getMonth(),d=today.getDate()-birth.getDate();if(d<0){m--;d+=new Date(today.getFullYear(),today.getMonth(),0).getDate()}if(m<0){y--;m+=12}byId("age_result").innerHTML=`<strong>${y} Years, ${m} Months, ${d} Days</strong>`}
function calcDateDiff(){let s=byId("date_start").value,e=byId("date_end").value;if(!s||!e){byId("date_result").innerHTML="Select both dates.";return}let days=Math.abs((new Date(e)-new Date(s))/(1000*60*60*24));byId("date_result").innerHTML=`<strong>${fmt(days,0)} Days</strong>`}
function lengthFactor(u){return {mm:.001,cm:.01,m:1,km:1000,inch:.0254,ft:.3048,yard:.9144,mile:1609.344}[u]||1}
function calcLength(){let meter=val("length_amount")*lengthFactor(byId("length_from").value);let out=meter/lengthFactor(byId("length_to").value);byId("length_result").innerHTML=`<strong>${fmt(out,6)} ${byId("length_to").value}</strong>`}
function tempToC(v,u){if(u==="c")return v;if(u==="f")return (v-32)*5/9;if(u==="k")return v-273.15}
function cToTemp(c,u){if(u==="c")return c;if(u==="f")return c*9/5+32;if(u==="k")return c+273.15}
function calcTemp(){let c=tempToC(val("temp_amount"),byId("temp_from").value);let out=cToTemp(c,byId("temp_to").value);byId("temp_result").innerHTML=`<strong>${fmt(out,3)} °${byId("temp_to").value.toUpperCase()}</strong>`}
function areaFactor(u){return {sqm:1,sqft:.092903,sqyd:.836127,acre:4046.8564224,hectare:10000}[u]||1}
function calcArea(){let sqm=val("area_amount")*areaFactor(byId("area_from").value);let out=sqm/areaFactor(byId("area_to").value);byId("area_result").innerHTML=`<strong>${fmt(out,6)} ${byId("area_to").value}</strong>`}
function heightToMeters(){let u=byId("height_unit").value;if(u==="cm")return val("height_main")/100;if(u==="m")return val("height_main");if(u==="inch")return val("height_main")*.0254;if(u==="ftin")return((val("height_main")*12)+val("height_extra"))*.0254;return 0}
function weightToKg(){let u=byId("weight_unit").value,v=val("weight");if(u==="kg")return v;if(u==="g")return v/1000;if(u==="lb")return v*.45359237;return 0}
function updateBMIInputs(){let u=byId("height_unit")?.value,extra=byId("height_extra_wrap"),lbl=byId("height_main_label");if(!u||!extra||!lbl)return;if(u==="ftin"){extra.classList.remove("hidden");lbl.textContent="Feet"}else{extra.classList.add("hidden");lbl.textContent=u==="cm"?"Height in CM":u==="m"?"Height in Meter":"Height in Inch"}}
function calcBMI(){updateBMIInputs();let m=heightToMeters(),kg=weightToKg(),bmi=kg/(m*m);if(!isFinite(bmi)||bmi<=0){byId("bmi_result").innerHTML="Please enter valid height and weight.";return}let cat=bmi<18.5?"Underweight":bmi<25?"Normal weight":bmi<30?"Overweight":"Obesity";byId("bmi_result").innerHTML=`<strong>BMI: ${fmt(bmi,2)}</strong><br><strong>Category: ${cat}</strong>`}
function calcBMR(){let kg=weightToKg(),cm=heightToMeters()*100,age=val("bmr_age"),gender=byId("bmr_gender").value;let bmr=gender==="male"?10*kg+6.25*cm-5*age+5:10*kg+6.25*cm-5*age-161;byId("bmr_result").innerHTML=`<strong>BMR: ${fmt(bmr,0)} calories/day</strong>`}
document.addEventListener("DOMContentLoaded",()=>{if(byId("siteSearch"))byId("siteSearch").addEventListener("input",filterCards);document.querySelectorAll("input,select").forEach(el=>el.addEventListener("input",runPage));runPage()})
function runPage(){let p=document.body.dataset.page;if(p==="kgmt")calcKgMt(); if(p==="liter")calcLiterMt(); if(p==="sm3")calcSm3Mt(); if(p==="gst")calcGST(); if(p==="bmi")calcBMI(); if(p==="bmr")calcBMR(); if(p==="percentage")calcPercentage(); if(p==="discount")calcDiscount(); if(p==="profit")calcProfitLoss(); if(p==="emi")calcEMI(); if(p==="sip")calcSIP(); if(p==="fd")calcFD(); if(p==="age")calcAge(); if(p==="datediff")calcDateDiff(); if(p==="length")calcLength(); if(p==="temp")calcTemp(); if(p==="area")calcArea(); if(p==="emd")calcPercentAmount("emd_base","emd_percent","emd_result","EMD Amount"); if(p==="pbg")calcPercentAmount("pbg_base","pbg_percent","pbg_result","PBG Amount"); if(p==="sd")calcPercentAmount("sd_base","sd_percent","sd_result","Security Deposit"); if(p==="margin")calcPercentAmount("margin_base","margin_percent","margin_result","Margin Amount"); if(p==="l1")calcPercentAmount("l1_base","l1_percent","l1_result","Difference Amount")}